version: "3.1"
services:
 
  prometheus:
    image: "prom/prometheus:${PROMETHEUS_TAG}"
    hostname: prometheus
    container_name: localprometheus
    volumes:
      - ./prom_volume/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    
  grafana:
    image: "grafana/grafana:${GRAFANA_TAG}"
    container_name: localgrafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
    ports:
      - "3000:3000"
    volumes:
      - ./graf_volume/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    links:
      - prometheus
  
  scrapeapp:
    image: dejanualex/go_promexporter:${EXPORTER_TAG}
    hostname: goexporter
    container_name: localgoexporter
    ports:
      - "5000:5000"
    links:
      - prometheus

  mynode:
    image: prom/node-exporter
    hostname: nodeexporter
    ports:
      - "9100:9100"
    links:
      - prometheus

volumes:
  prom_volume:
  graf_volume:
  



