version: '3.4'
services:
  prometheus:
    image: "dejanualex/prometheus:${PROMETHEUS_TAG}" 
    hostname: prometheus
    container_name: localprometheus
    command:
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    
  grafana:
    image: "grafana/grafana:${GRAFANA_TAG}"
    container_name: localgrafana
    volumes:
      - ./graf_volume:/etc/grafana/provisioning/datasources/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
    ports:
      - "3000:3000"
    links:
      - prometheus
  
  scrapeapp:
    image: dejanualex/go_promexporter:${EXPORTER_TAG}
    hostname: goexporter
    # build:
    #   context: ./go_exporter
    container_name: localgoexporter
    ports:
      - "5000:5000"
    links:
      - prometheus

  mynode:
    image: prom/node-exporter
    hostname: nodeexporter
    ports:
      - "9100:9100"
    links:
      - prometheus